### ISSUE TITLE
actionsの調整

### ISSUE THREAD

**Issue by light-planck** [light-planck/nemmy#21]
- lint, formatは修正せずに、検知だけするようにする
- 毎週bun updateする
- CodeQLをymlとして書く
- Dependabotをアサインしないようにする

```yml
name: Assign PR author

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to author
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (context.payload.pull_request.user.login !== 'dependabot[bot]') {
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                assignees: [context.payload.pull_request.user.login]
              })
            }
```
